### ISSUE TITLE
Make test returnes one failure

### ISSUE THREAD

**Issue by fatexs** [l0b0/unrarr#5]
root@brick /opt/git/unrarr (git)-[master] # make test
/opt/git/unrarr/test.sh
test_simple
test_wrong_params
test_verbose
test_delete
test_delete_standard_multipart_archives
ASSERT:No output on standard error
test_delete_extension_multipart_archives

Ran 6 tests.

FAILED (failures=1)
Makefile:13: recipe for target 'test' failed
make: *** [test] Error 1

ubuntu 17.04

**Comment by l0b0** [comment]
I tried to reproduce, but I'm afraid `rar` is a bit of a pain to install on Arch Linux, and proprietary too AFAICT. I also haven't used this tool for at least five years myself, so I'm probably the wrong person to keep maintaining it. So I'm going to declare this tool no longer maintained. Sorry, but I hope you understand.
